import {
    ChronaxieEnum,
    ClefEnum,
    KeySignatureEnum,
    MusicalAlphabetEnum,
    NoteTypeEnum,
    MsSymbolTypeEnum,
    TimeSignatureEnum, MusicScoreShowModeEnum
} from './musicScoreEnum.ts';
import type {MusicScore} from "./types.d.ts";

const data: MusicScore = {
    showMode: MusicScoreShowModeEnum.StandardStaff,
    multipleStavesArray: [{
        singleStaffArray: [{
            measureArray: [{
                options: {},
                msSymbolArray: [{
                    clef: ClefEnum.treble,
                    type: MsSymbolTypeEnum.Clef,
                    options: {},
                    measureRelativeRect: {},
                }, {
                    timeSignature: TimeSignatureEnum['4/4'],
                    type: MsSymbolTypeEnum.TimeSignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    keySignature: KeySignatureEnum.c,
                    type: MsSymbolTypeEnum.KeySignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C3,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                },]
            }, {
                options: {},
                msSymbolArray: [{
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                },]
            }, {
                options: {},
                msSymbolArray: [{
                    clef: ClefEnum.treble,
                    type: MsSymbolTypeEnum.Clef,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                },]
            }, {
                options: {},
                msSymbolArray: [{
                    clef: ClefEnum.treble,
                    type: MsSymbolTypeEnum.Clef,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    timeSignature: TimeSignatureEnum['4/4'],
                    type: MsSymbolTypeEnum.TimeSignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    keySignature: KeySignatureEnum.c,
                    type: MsSymbolTypeEnum.KeySignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                },]
            }]
        }]
    }, {
        singleStaffArray: [{
            measureArray: [{
                options: {},
                msSymbolArray: [{
                    clef: ClefEnum.treble,
                    type: MsSymbolTypeEnum.Clef,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    timeSignature: TimeSignatureEnum['4/4'],
                    type: MsSymbolTypeEnum.TimeSignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    keySignature: KeySignatureEnum.c,
                    type: MsSymbolTypeEnum.KeySignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                },]
            }, {
                options: {},
                msSymbolArray: [{
                    clef: ClefEnum.treble,
                    type: MsSymbolTypeEnum.Clef,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    timeSignature: TimeSignatureEnum['4/4'],
                    type: MsSymbolTypeEnum.TimeSignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    keySignature: KeySignatureEnum.c,
                    type: MsSymbolTypeEnum.KeySignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                },]
            }, {
                options: {},
                msSymbolArray: [{
                    clef: ClefEnum.treble,
                    type: MsSymbolTypeEnum.Clef,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    timeSignature: TimeSignatureEnum['4/4'],
                    type: MsSymbolTypeEnum.TimeSignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    keySignature: KeySignatureEnum.c,
                    type: MsSymbolTypeEnum.KeySignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                },]
            }, {
                options: {},
                msSymbolArray: [{
                    clef: ClefEnum.treble,
                    type: MsSymbolTypeEnum.Clef,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    timeSignature: TimeSignatureEnum['4/4'],
                    type: MsSymbolTypeEnum.TimeSignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    keySignature: KeySignatureEnum.c,
                    type: MsSymbolTypeEnum.KeySignature,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                }, {
                    musicalAlphabet: MusicalAlphabetEnum.C4,
                    chronaxie: ChronaxieEnum.quarter,
                    type: MsSymbolTypeEnum.NoteHead,
                    options: {},
                    measureRelativeRect: {}
                },]
            }]
        }]
    }]
};
export default data;